CREATE TABLE BANK(bankcode varchar(3),bankname varchar(10)not null,headoffice varchar(20),branches int,PRIMARY KEY(bankcode));

CREATE TABLE BRANCH(branchid int,branchname varchar(10) DEFAULT 'New Delhi',bankid varchar(3),PRIMARY KEY(branchid),FOREIGN KEY(bankid) REFERENCES BANK(bankcode));

INSERT INTO BANK VALUES('10A','SBT','ERNAKULAM',3);
INSERT INTO BANK VALUES('10B','STATE BANK','ERNAKULAM',1);
INSERT INTO BANK VALUES('10C','HDFC','KOTTAYAM',1);
INSERT INTO BANK VALUES('10D','ICICI','KOTTAYAM',4);
INSERT INTO BRANCH VALUES(101,'KOTTAYAM','10C');
INSERT INTO BRANCH VALUES(102,'ERNAKULAM','10B');


DELETE FROM BANK WHERE BANKNAME='SBT';

ALTER TABLE branch
DROP PRIMARY KEY; 

CREATE VIEW BANK_HEAD_OFFICE AS
SELECT BANK.BANKCODE, BANK.BANKNAME, BANK.HEADOFFICE, BANK.BRANCHES, BRANCH.BRANCHID
FROM BANK,BRANCH
WHERE BANK.HEADOFFICE = 'ERNAKULAM';

CREATE VIEW bank_branch AS
SELECT BANK.BANKCODE, BANK.BANKNAME, BANK.HEADOFFICE, BANK.BRANCHES, BRANCH.BRANCHID
FROM BANK,BRANCH
WHERE BANK.HEADOFFICE = 'KOTTAYAM';



